### ISSUE TITLE
POI layer

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#106]
Requests to show Points Of Interest (POI) on the map for tour planning:
- youth hostels ([Hostel overlay (Groups)](https://groups.google.com/d/msg/osm-android-bikerouting/OyeMk1TzofM/nopPpA83czgJ))
- Historic objects (#105)

It would be nice to have a general Overpass API POI layer with some UI to select/filter for specific POIs/categories. Not aware of any plugin for the UI part though.

Maybe utilizing tag hierarchies, icons and translations for selection and popup content from POI apps or [editor presets](https://github.com/openstreetmap/iD/blob/master/data/presets/README.md)?

## Overpass layers

- [leaflet-nectarivore](https://github.com/osmlab/leaflet-nectarivore)
- [overpass-layer](https://github.com/plepe/overpass-layer) + [overpass-frontend](https://github.com/plepe/overpass-frontend)
- [leaflet-overpass-layer](https://github.com/GuillaumeAmat/leaflet-overpass-layer)

## POI apps

- [OpenStreetBrowser](https://github.com/plepe/OpenStreetBrowser)
- [osm24](https://github.com/dotevo/osm24/) - http://osmapa.pl/osm24
- [Unterkunftskarte](http://unterkunftskarte.de/#14/51.0700/13.7299) - no repository
- [openpoimap](https://github.com/marczoutendijk/openpoimap) - http://openpoimap.org/, OpenLayers

## Router with POIs examples

- [Openrouteservice Maps](https://maps.openrouteservice.org/) - pin button on the right, own DB
- [Komoot](https://www.komoot.de/plan/) - click in search bar, closed source
- [Naviki](https://www.naviki.org/de/naviki/route-planen/) - button top right, closed source

**Comment by hugobqd** [comment]
When I prepare a mountain bike ride with brouter-web, I always look for drinking water on my way with overpass turbo. It would be awesome to have it and other requests into brouter-web

This are my four request : 
`[man_made=water_tap]
  [amenity=drinking_water]
  [amenity=toilets][drinking_water!=no]
  [drinking_water=yes]`

**Comment by stesie** [comment]
Hej, just wanted to let you know that I've started working on this.

So far you can enable an extra overpass layer + either enter a custom overpass query (updated on textarea blur) or choose from the (yet little) template list. The marker popup definitely needs more content, ... and generally early feedback is welcome :-)

Currently the build fails on the branch since `gulp-uglify` stumples over `let` variables used in `overpass-layer`. As a first time contributor to the project I'm still wondering which language level this project is actually targeting. So this might also need some work.

**Comment by nrenner** [comment]
Great, thanks for the announcement, looking forward to it!

I will see if I can have a look at your branch, but got a bit of a backlog right now.

We're still not using ES6 yet, see #249 and discussion in #250. Already was planning to have another look at our user agents and to decide if we should either just drop IE11 and other legacy browser support or simply use standalone Babel with the full polyfill package as an intermediate step to using a bundler.

**Comment by nrenner** [comment]
Some thoughts that came to mind:
- just saw that [plepe/overpass-layer](https://github.com/plepe/overpass-layer/blob/master/LICENSE) seems to be GPL licensed, which would be incompatible with our MIT license
- before you start formatting OSM tags for popup output (sanitizing, links, address formatting, translation, images, ...): don't know if those tools already support that or if there is a library, but we should do some research or borrow from some license-compatible POI maps
- a nice addition might be not only to query the viewport bbox, but alternatively offering to query POIs along the route with Overpass API [around](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#Relative_to_other_elements_.28around.29) feature that can also take a list of lat/lon pairs.

**Comment by stesie** [comment]
Ouch, ... I haven't checked the license but just followed the list in the initial post and noticed that `plepe/overpass-layer` looks better maintained. Both other options have their last commit in 2018 and there also are no better maintained forks.

So thanks for your fast response to keep me from going further that route :)

Towards popup formatting my first idea was to just list the key/value pairs of the node/area and maybe go fancier over time. I just had a brief look into the `leaflet-overpass-layer` alternative, which BTW does just that :)

I like the idea with the around feature, I'll have a closer look into the aforementioned alternative and whether it's possible to do so. But looks promising so far. I'll also have a look if it'd be feasible to have a "execute query" button instead of querying implicitly (which is likely to cause unneeded/unwanted overpass api queries)

**Comment by bagage** [comment]
Regarding the license issue, it might be worth asking about it on @plepe project - maybe it can be changed to some compatible MIT license instead?

**Comment by nrenner** [comment]
> Regarding the license issue, it might be worth asking about it on @plepe project - maybe it can be changed to some compatible MIT license instead?

Done in [overpass-layer#1](https://github.com/plepe/overpass-layer/issues/1).

**Comment by nrenner** [comment]
> Ouch, ... I haven't checked the license but just followed the list in the initial post 

Sorry, my bad, I should have checked before listing them.

I also think that `plepe/overpass-layer` is the most advanced and probably the only one that takes Overpass [rate limiting](https://dev.overpass-api.de/overpass-doc/en/preface/commons.html#quotas) into account, e.g. by query delays and explicitly handling 429 responses.

> I'll also have a look if it'd be feasible to have a "execute query" button instead of querying implicitly (which is likely to cause unneeded/unwanted overpass api queries)

Sounds like a good idea to me.

**Comment by plepe** [comment]
I also think that it's rather advanced (actually [overpass-frontend](https://github.com/plepe/overpass-frontend)) with caching, splitting of queries, retries, arbitrary geojson boundary for queries, .... You can even load a .osm file and run your overpass queries on this.

There's a drawback though, it can handle only rather basic queries, as it parses the query to load results from the cache. No sets or distance. But it should be okay for most cases.
