### ISSUE TITLE
[0.7.0] Let user set route color; Compute ETA; Hide waypoints

### ISSUE THREAD

**Issue by Shohreh** [nrenner/brouter-web#138]
Hello,

I have the following suggestions:

- [ ] 1. Let user change route color from pink to any color they want; I guess a cookie is an easy way to remember a user — and their preferences — without requiring them to log on

- [ ] 2. Compute ETA (eg. 13km @ 15km/h ~  52mn) https://github.com/abrensch/brouter/issues/6 https://github.com/abrensch/brouter/issues/125

- [ ] 3. Hide waypoints, à la Google Maps directions:
![image](https://user-images.githubusercontent.com/1451988/66065432-aa0e1880-e547-11e9-926c-df8a98d052e8.png)

Cheers,

**Comment by abrensch** [comment]
There is an ETA display in brouter-web already, and for the car-profiles (car-eco/car-fast) there's data as well.  car-eco (based on 90km nominal speed) gives quite good travel-time estimations, car-fast understimates because it used 160km nominal speed.

There's not yet ETA data for bike or hike profiles, but there's an ETA issue in the brouter-repository: https://github.com/abrensch/brouter/issues/6

**Comment by bagage** [comment]
I'm creating separate issues for each points, since they are unrelated.

1. https://github.com/nrenner/brouter-web/issues/246
2. It is already being worked on and implemented?
3. https://github.com/nrenner/brouter-web/issues/247

Closing this one then! Thanks.

**Comment by Phyks** [comment]
2 is indeed implemented already :)
