### ISSUE TITLE
Wrong version under 0.7.0 tag

### ISSUE THREAD

**Issue by Phyks** [nrenner/brouter-web#140]
Hi,

I think the 0.7.0 tag is one commit ahead of what it should be and the version in it is still 0.6.3: https://github.com/nrenner/brouter-web/blob/0.7.0/index.html#L17.

No big deal, it seems the rest of the code is fine and agree with 0.7.0. I'm just opening an issue to let you know (feel free to close it) :)

Best,

**Comment by nrenner** [comment]
Thanks for reporting, will have a look at it.

**Comment by nrenner** [comment]
I could move the tag, as getting the wrong version number with the tag is misleading, but moving might also cause trouble, see e.g. ["Moving tags is generally discouraged [...]"](https://stackoverflow.com/a/25849828/4642540). :confused:

**Comment by Phyks** [comment]
Yes, don't worry too much about it, it's not really a big deal. I'd tend to say it depends a lot on the planning for the next release, as most people are likely to just use the latest version and the problem will be more or less solved at this moment.

The issue was rather for people wondering about this to quickly have an endpoint with the info that the code is fine but the version is not updated :)

**Comment by Phyks** [comment]
Note: Same for 0.8.0 :) https://github.com/nrenner/brouter-web/blob/0.8.0/index.html#L17

**Comment by nrenner** [comment]
Thanks, I noticed as well: 
The [tag 0.8.0](https://github.com/nrenner/brouter-web/releases/tag/0.8.0) is on the previous commit f01df99 instead of the "release: 0.8.0" e381a92.

Last time I thought this was because the push had failed and I had continued manually.

But it might be an issue with the gulpfile, that the `commit` and `tag` commands are running in parallel instead of sequentially, see `gulp release` log:

```
[18:01:33] Starting 'release:commit'...
[18:01:33] Finished 'release:commit' after 735 μs
[18:01:33] Starting 'release:tag'...
[18:01:33] Finished 'release:tag' after 6.26 ms
[18:01:33] Starting 'release:push'...
[18:01:33] Finished 'release:push' after 7.38 ms
```

The `release:commit` task finished very quickly, so it maybe runs the task's stream in async while continuing with the `release:tag` task.

I added a missing `return` in the hope to fix this (untested).
