### ISSUE TITLE
Cost (mean cost factor)

### ISSUE THREAD

**Issue by debyos** [nrenner/brouter-web#166]
Dear All,
could you explain what _cost_ and _mean cost factor_ are?
I can see that [there is already an issue](https://github.com/nrenner/brouter-web/issues/39) with it but for me it is a bit obscure and I would like to translate it well.
Thanks in advance

**Comment by poutnikl** [comment]
BRouter evaluate "desireness" of road segments by providing a "cost" of such a segment as an equivalent length, that is usually somewhat higher than its physical length. 

E.g a road 3 km long has bad surface, so take it as 5 km. Ah, it goes uphill, so take it as 8 km. Then the cost of this 3km road is 8km. 

The sum of these costs gives the cost of a route as the total equivalent route cost.
BRouter searches for a route with the minimal cost.

The mean cost factor is ratio of the route cost and the route length. It is the measure of the route quality, whatever this quality means. For ideal quality it is 1.0.

**Comment by debyos** [comment]
Thank you!
And then the _mean cost factor_ of the 3 km long route costing 8 km mentioned by you is 8/3, i.e. 2,666?

**Comment by poutnikl** [comment]
The mean cost factor is for the whole route. If that 3km road would be the whole route, then yes, the mean cost factor would be 8/3= 2.666... .

**Comment by debyos** [comment]
OK, thanks. I coined a translation.

**Comment by gnbl** [comment]
Please add an explanation for this to the GUI.
Maybe instead of having mouseovers for the SI units (km, h, kWh, m) generate alternative outputs  and an explanation for each output (Distance, Travel time, Energy, Ascend, Cost). 
E.g. by clicking on the bar it will become larger, like the elevation chart, and show that info below the values.
Optionally allow changing units via this interface.
Thanks!
