### ISSUE TITLE
Missing nogo weight when loading nogos

### ISSUE THREAD

**Issue by Phyks** [nrenner/brouter-web#174]
Hi,

It seems loading nogos from a GeoJSON while specifying a (positive) weight does not work and the URL for the query to the BRouter server is not updated accordingly.

It seems that when loading GeoJSON data [here](https://github.com/nrenner/brouter-web/blob/master/js/index.js#L416), the properties of the features in the GeoJSON object are not loaded by Leaflet (they should be loaded into options in Leaflet, for [this part](https://github.com/nrenner/brouter-web/blob/master/js/router/BRouter.js#L338) to work).

I am really not sure what is happening here, I'm almost sure this was fully tested and working when the PR got merged. Maybe this is due to a Leaflet update?

Best,

**Comment by nrenner** [comment]
`feature.properties` are not loaded into `layer.options`, only the `options` object that is passed to the `GeoJSON` is copied to all layers.

The commit history is lost because of squashing, but I think you first passed `nogoWeight` as an option to `L.geoJson`, and later changed it to `onEachFeature` to read nogoWeight from the file?

https://github.com/nrenner/brouter-web/blob/5f89287a97b0534fdc3fc3e0b2567cd0a47460f5/js/index.js#L417-L421

I would prefer to manually set the layer option here instead of PR #175, something like this:

```js
                    onEachFeature: function (feature, layer) {
                        layer.options.nogoWeight = feature.properties.nogoWeight || nogoWeight;
                    }
```

**Comment by Phyks** [comment]
Indeed, this is a very nice idea to have it handled this way. I updated the PR accordingly, thanks for the feedback!
