### ISSUE TITLE
No calculation of distance, travel time, etc.

### ISSUE THREAD

**Issue by Umea123** [nrenner/brouter-web#203]
No calculation of distance, travel time, etc. in Northern Europe / north of the 60 ° latitude.

**Comment by nrenner** [comment]
Thanks for reporting.

Example:
http://brouter.de/brouter-web/index.html#map=8/70.813/24.620/osm-mapnik-german_style&lonlats=25.740967,71.13454;23.642578,70.678153

This probably is because of no [elevation data](http://srtm.csi.cgiar.org/srtmdata/) beyond 60 degrees north and south and the recent change to remove elevation points with no data (#147).

When no elevation points remain, the Elevation plugin throws an exception because of empty data:

```
BRouter.js:188 Error: no data in parameters
    at e._calculateFullExtent (L.Control.Elevation.js:648)
    at e._applyData (L.Control.Elevation.js:745)
    at e.addData (L.Control.Elevation.js:668)
    at e.update (Elevation.js:80)
    at n (index.js:245)
    at o (L.Routing.js:340)
    at e.<anonymous> (Routing.js:317)
    at Object.callback (L.Routing.js:396)
    at r (async.js:798)
    at async.js:32 "..."
```

[opoto/Leaflet.Elevation - src/L.Control.Elevation.js#L645-L649](https://github.com/opoto/Leaflet.Elevation/blob/d3a7bcbef62261138417792900d63c3091c73dbe/src/L.Control.Elevation.js#L645-L649):
```js
    _calculateFullExtent: function(data) {


        if (!data || data.length < 1) {
            throw new Error("no data in parameters");
        }
```

Which prevents the subsequent stats update code to be executed.

With the older version at damsy.net there are some "NaN" errors (Chrome) / warnings (Firefox) in the console, but don't seem to matter:
https://brouter.damsy.net/latest/#map=8/70.813/24.620/osm-mapnik-german_style&lonlats=25.740967,71.13454;23.642578,70.678153

**Comment by nrenner** [comment]
There is another smaller issue, that the beginning of a route with missing data is not shown in the diagram, not really wrong but misleading:
http://brouter.de/brouter-web/#map=12/59.9891/5.5060/Stamen.Terrain&lonlats=5.51033,60.028328;5.506211,59.9679

All this confirms my initial doubt, if simply removing the data points is really the right approach. When searching for "d3 missing data" I found the d3 [`area.defined`](https://github.com/d3/d3-shape/blob/v1.3.4/README.md#area_defined) ([v3.x](https://github.com/d3/d3-3.x-api-reference/blob/master/SVG-Shapes.md#area_defined)) accessor function, that allows to skip missing values and render them as gaps.

Implementation using `defined` and additional missing altitude handling in [9ae6a3c](https://github.com/nrenner/Leaflet.Elevation/commit/9ae6a3caef5f01abb3e55e05376df2e0046f7449).

**Comment by Phyks** [comment]
This has just been reported again on the Android bikerouting mailing list (you probably saw it). This can be reproduced at the moment with http://brouter.de/brouter-web/#map=7/61.700/16.490/standard&lonlats=15.639107,60.60576;17.302227,62.390278.

Not sure if brouter-web on brouter.de is already up to date and patched?

**Comment by nrenner** [comment]
Seen it, thanks. Not deployed yet. It is part of [Milestone for version 0.10.3](https://github.com/nrenner/brouter-web/milestone/11), which is still open and brouter.de is still v0.10.2.
