### ISSUE TITLE
OpenTopoMap zoom limit

### ISSUE THREAD

**Issue by poutnikl** [nrenner/brouter-web#21]
OpenTopoMap has zoom limit 15. 

For higher zooms, it could be more useful to just zoom Z15 tiles, or refuse to zoom, instead of providing blank map.

this Blank Z16 already does have greyed out the zoom in, so it kicks in just 1 level late.

**Comment by nrenner** [comment]
Yes, that's a bit unfortunate. I changed maxZoom from 15 to 16 some time ago (now active with 0.5.0) because OpenTopoMap has added z16 support.

But now it's running on a fallback server which does not support z16 and it's unclear for how long (see [German Forum](http://forum.openstreetmap.org/viewtopic.php?pid=509454#p509454)).

Probably going to change back to z15.

**Comment by poutnikl** [comment]
Could the web be coded to be adaptive to current map source status ( probably applicable to any mapsource ) ?

**Comment by nrenner** [comment]
Not worth the effort IMO, set it back to z15 for now.
