### ISSUE TITLE
Let user export GPX with any turnInstructionStyle

### ISSUE THREAD

**Issue by Phyks** [nrenner/brouter-web#223]
Hi,

I've recently discovered that BRouter supports different GPX export format, https://github.com/phyks/brouter/blob/5a1f7dccedc0c97f21166f0b661d9f562b8f7829/misc/profiles2/trekking.brf#L17. 

Depending on the `turnInstructionMode` variable, this can be either no turn instructions, locus, OsmAnd etc. What about letting users overloading this when downloading the GPX trace from BRouter-web, instead of having to dig into the profile?

Actually, this might be something worth discussing at the BRouter level. The profiles mix global variables (used and defined across any profiles such as `turnInstructionMode` or `considerTurnRestrictions`), local variables (customizing the behavior of a particular profile) and auxiliary variable (for readability of the profiles).

It could be very useful to have a nice UI for at least the BRouter-global ones (and maybe the local ones, provided they can be parsed easily from the profiles, which is not currently the case). This would probably improve BRouter-web accessibility and ease of use a lot! :)

Best,

**Comment by nrenner** [comment]
@abrensch mentioned that the BRouter Android intent interface would already support profile parameters, but I don't know any details and what it would take to make them passable from BRouter-Web and override the profile default values.

Also not sure about the UI. Would that be a generic one parsing available parameters from the current profile? Or fixed inputs where it makes sense, e.g. `turnInstructionMode` in the export dialog. Or a combination of both?

The primary goal for having profile parameters would be to get rid of profile variants in the dropdown (trekking ignore cycleroutes/steep/no ferries/no steps/...) and use checkbox options instead.

**Comment by abrensch** [comment]
There are some undocumented URL-params that I use for an e-mobility showcase:

see https://github.com/abrensch/brouter/blob/master/brouter-server/src/main/java/btools/server/RouteServer.java

- timode : the turn-instruction-mode
- heading: the current moving direction
- profile:xxx : overwrite parameter xxx *** of the kinematical model (=car routing) ***

So that' currently only a hack and profile:xxx does not overwrite params of the "StdModel", and there are other hacks, e.g. does profile:vmax at the same time requests the speed-limit-profile.

But if that should become a feature I could of course remove the hacks and make it more consistent.

regards, Arndt

**Comment by Phyks** [comment]
> Also not sure about the UI. Would that be a generic one parsing available parameters from the current profile? Or fixed inputs where it makes sense, e.g. turnInstructionMode in the export dialog. Or a combination of both?

I was thinking about having it in the settings (currently profile editing) tab. This tab could be split into two parts:
1. A user-friendly clickable part to edit the profile settings (use turn restrictions, stick to cycle route etc).
2. An "advanced user editing" part, showing the full profile edition textarea as currently done.

> There are some undocumented URL-params that I use for an e-mobility showcase

That's nice and the kind of thing I had in mind. I think a quick and easy implementation could be to have three aliases for the "assign" keyword in the BRouter profiles: 
- Keep "assign" for local variables, defined in a specific profile and used only in it.
- Have a "global" keyword for variables used in BRouter core itself (typically turn instruction mode, `considerTurnRestrictions` etc).
- Have a "define" for constants defined in a profile top level and aimed at being easily changed by everyone (weights, coefficients, stick to cycle routes, etc).

This would probably help increase readability of BRouter profiles as well as let third party apps such as BRouter-web parse the profiles and edit it live with a user friendly interface. What do you think @abrensch?

**Comment by Phyks** [comment]
Actually, I missed the fact that we already have a `---context:global` section, so this is probably already doable at the moment. I already have a kind of PoC.

**Comment by zossebart** [comment]
We had a similar discussion in the LocusMap Helpdesk some years ago. The developer of Locus decided to only allow to change 4 predefined profile parameters through the UI which were considered most common between profiles at this time: avoid_motorways , avoid_toll, is_wet , avoid_unpaved. 
You have to mark these parameters in the profile by a special comment after the assignment (for example "# %avoid_motorways%") for Locus to parse it and offer an UI for it.
See the discussion here: [https://help.locusmap.eu/topic/dynamic-brouter-profile-configuration](url)

There were also ideas to enhance this to allow the profile developer to specify some sort of label string, which would be displayed by the UI instead of the sometimes not very readable parameter name. Also, the client should parse the default value and initially use it (which Locus does not).

Maybe we could agree on something similar, so that the profile developer has the choice for which parameters to offer an UI.

If we get to a consensus here, maybe other client developers (I think of LocusMaps developer) also implement or enhance their UI for this, reducing the need for multiple profiles which only differ by one or few parameters (which is the case with my mtb profiles).

**Comment by Phyks** [comment]
> Maybe we could agree on something similar, so that the profile developer has the choice for which parameters to offer an UI.

Wow, I completely missed these discussions on the Locus side. I really think it would be a really nice thing to have a quite "standard" procedure here to try to factor profiles and limit the number of different profiles to maintain, just differing by a simple configuration option.

Do you know if anything is already implemented in Locus?

**Comment by zossebart** [comment]
Yes, in Locus there is a limited support for 4 predefined profile parameters:

avoid_motorways , avoid_toll, is_wet , avoid_unpaved

When they are marked with the special comment syntax, Locus displays switches in it's navigation settings to toggle them between 0 and 1. It's limited to this simple on/off switches and not for arbitrary parameters but only for the 4 predefined ones. But maybe this could be enhanced once there is a consensus about the syntax.
The Locus developer denied support for arbitrary parameters because he feared that this would be too complex for the average user. Therefore, he restricted the implementation to the 4 mentioned common/most used parameters. But maybe one could hide additional parameter settings UI in an expert-menu or something...?

**Comment by Phyks** [comment]
We could easily extend the Locus syntax and hopefully they can integrate it furthermore if they think this is worth for them.

My proposal would be to only offer in the UI the parameters with a syntax such as the one proposed by @abrensch in the Locus forum:

```
assign <PARAMETER> = <VALUE>  # %config-option% Name | Description
```

such as

```
assign  avoid_toll  = false   # %config-option% Toll roads | Allows toll roads
```

or

```
assign  uphillcost  = 10   # %config-option% Uphill cost | Cost for going uphill
```


@nrenner If you are fine with this, I can definitely edit this PR to limit it to this syntax and offer a proper configuration UI.

@abrensch What do you think about it? It would probably be interesting (in my opinion) to edit the profiles in BRouter (https://github.com/abrensch/brouter/tree/master/misc/profiles2) to use this syntax (I can write a PR for this). Ideally, we could probably remove the duplicated profiles there (we could replace them with a single version of the profile and a script to generate the variants, so that the APK build keeps all the current profiles but the repository has a single profile of each type).

**Comment by nrenner** [comment]
I'm all for having a special syntax to mark parameters, but:

1. I find `%config-option%` too long and would prefer e.g.
   -  a single character to mark a parsable comment, like `#%`:  
      ```
      assign <PARAMETER> = <VALUE>  #% Name | Description
      ```
   - or putting the Name in %:  
      ```
      assign <PARAMETER> = <VALUE>  # %Name% | Description
      ```
2. type information / allowed values is missing (we want more than just boolean), e.g. in brackets (would need further thoughts and definition):
   * boolean: `[0|1]` or `[true|false]` (checkbox)
   * number (range), e.g.: `[1-]` (input field, maybe with validation)
   * options list: `[0=none, 1=auto-choose, 2=locus-style, 3=osmand-style]` (dropdown/radio)

**Comment by zossebart** [comment]
I agree. The syntax could be shorter. But one big topic remains unsolved: what about translations of name or at least description? If we should find a syntax for this, couldn't this bloat up profiles?
 Also, your suggestions for type information and value range sound reasonable. I assume value ranges would be restricted to integer-values?

**Comment by Phyks** [comment]
Having a single extra character (`#%`) is very appealing but I'd like to keep the syntax as compatible with the current Locus syntax as possible, just extending it.

What about:

```
assign <PARAMETER> = <VALUE>  # %<NAME>% | <DESCRIPTION> | <TYPE>
```

* `<NAME>` would have to match `<PARAMETER>`, at least for the current Locus supported settings.
* `<DESCRIPTION>` could be anything to describe the setting. Optional, can be omitted.
* `<TYPE>` would be  `boolean`, `number` or something like `[0=none, 1=auto-choose, 2=locus-style, 3=osmand-style]` for an option list. Optional, not having it would imply `number`.

In the future, I think name and description could be localized by passing them to `i18next`.

**Comment by nrenner** [comment]
As for Locus compatibility: how and what does Locus actually parse? The [example given](https://help.locusmap.eu/topic/dynamic-brouter-profile-configuration#comment-32818) does not contain ` Name | Description`: 

    assign avoid_motorways        0 # %avoid_motorways%

Maybe we can put the `%<NAME>%` (which is actually `%<PARAMETER>%`) at the end of the comment (not sure if really better)?

    assign <PARAMETER> = <VALUE>  # <DESCRIPTION> | <TYPE> | %<NAME>%

**Comment by nrenner** [comment]
> \<TYPE\> would be boolean, number or something like [0=none, 1=auto-choose, 2=locus-style, 3=osmand-style] for an option list. Optional, not having it would imply number.

I guess that's also Ok, no strong opinions on this.

**Comment by Phyks** [comment]
> As for Locus compatibility: how and what does Locus actually parse? The example given does not contain `Name | Description`:

As far as I understood, so far, Locus only supports a limited range of parameters with the syntax `assign parameter = value # %parameter%`. I think if anything else is on the line, it will simply ignore it as long as `%parameter%` is present in the comment.

That's why I used the syntax

```
assign <parameter> = <value> # %parameter% | description | type
```

so that it should stay compatible with the current Locus implementation for supported options. See https://github.com/Phyks/brouter/blob/fc13c5c1594575cc92b912536c7fa9b77bd72d1c/misc/profiles2/trekking.brf#L12 for instance.

I'll double check this with Locus developpers.

> Maybe we can put the %<NAME>% (which is actually %<PARAMETER>%) at the end of the comment (not sure if really better)?

I'd rather have it in the beginning as `%<NAME>%` is always mandatory. Description and / or type could be omitted and is an extension of the current Locus schema.

**Comment by Phyks** [comment]
> I'll double check this with Locus developpers.

I've got a positive feedback from Locus side :) https://help.locusmap.eu/topic/dynamic-brouter-profile-configuration#comment-75863

**Comment by nrenner** [comment]
Thanks for asking, so we leave it as you suggested, that's also fine with me.

**Comment by EssBee59** [comment]
Hello,
I agree: the new feature is a good solution to get rid of profile variants!
Just for my understanding: The issue was initially created to enhance the Brouter-web?
But the feature is also (perhaps more!) interesting for the Brouter App:
Currently I have to edit the profile underway on my smartphone as exemple if I want to change the parameter "consider_elevation":
So, by selecting a profile in the brouter-app it would be nice in future to get the possibility to change the "new" Parameters as defined above….

**Comment by EssBee59** [comment]
an exemple to implement as app is given by Osmand when using a specific "routing.xml":
==>		### Setting parameters via OsmAnd UI
		
		The UI of OsmAnd automatically picks up those settings, if this document is deployed.
		Just declaring a boolean option is enough to show a checkbox in the navigation settings.
		
		Toggle the checkbox to see your custom profile in action!
		The appearing extra toggle is also useful to see the activation of your custom routing.xml.

**Comment by Phyks** [comment]
This is supported in Locus. There is probably some extra work to make it supported by OSMAnd.

I think we can close this one after #189 merge.
