### ISSUE TITLE
NogoAreas control doesn't work on mobile Chrome

### ISSUE THREAD

**Issue by zzptichka** [nrenner/brouter-web#259]
Can't draw the circle.
Android.
Works fine on mobile Firefox though.

**Comment by nrenner** [comment]
Thanks for reporting.

Can reproduce in the mobile view of Chrome Desktop, dragging is moving the map instead of drawing a circle.

**Comment by nrenner** [comment]
Nogo drawing doesn't work on mobile Chrome because Leaflet.Editable relies on L.Map.Tap handler for touch support (see also [Leaflet.Editable#108](https://github.com/Leaflet/Leaflet.Editable/pull/108)), but that handler is not added in browsers that support Pointer events like mobile Chrome (mobile Firefox doesn't).

It does work in current version 0.11.1 however, as Leaflet 1.6.0 has a bug that disables the pointer flag for all Webkit browsers (instead of just Safari) and therefore enables the Tap handler for Chrome also, which is already fixed in master though, see [Leaflet#6977](https://github.com/Leaflet/Leaflet/issues/6977).

The workaround is to add the Tap handler ourselves where needed and to only enable it for circle drawing.
