### ISSUE TITLE
Avoid Areas?

### ISSUE THREAD

**Issue by pcace** [nrenner/brouter-web#319]
Hi there, i am not quite sure wether i am right here to ask the question - i have also tried to ask in the google forum. 
so if its wrong to ask here - please delete this. 

So i just found this amazing project here. so i am trying to make a profile wich avoids certain areas - for example areas described in OSM as  "boundary=protected_area" Is there any way to achieve this functionality?

Thank you very much, 

pcace

**Comment by pcace** [comment]
I tried a little (not really working Workaround, but maybe someone has an idea?
What i did is to generate a geojson file like this: https://overpass-turbo.eu/s/Vw4, exportet it and then importet it to the brouter web client as nogo area.
Problem 1: it then does not have a lower priority, it simply is literally a NOGO area.
Problem 2: it produces extremely large files and so it works only for very very small areas...

... so not really a solution... :(

**Comment by nrenner** [comment]
[Please avoid cross-posting in multiple channels.]

Loading Nogos from  Overpass via GeoJSON file is what I would have suggested, there is no other way right now.

1. there is a weight setting in the dialog where you can set a cost factor for passing instead of fully blocking
2. yes, this approach is very limited, as it is passing all the data with every request to the server

There really should be a way to consider surroundings of ways (e.g. by polygon intersection) when building the routing data files and to add that information as artificial tags.

**Comment by nrenner** [comment]
Closing, as the "Load no-go areas" feature is what we can offer for this right now, and further improvements would need to be made on the backend, see [Consider surroundings ·  brouter#258](https://github.com/abrensch/brouter/issues/258).
