### ISSUE TITLE
Exporting to ANT+/Garmin FIT

### ISSUE THREAD

**Issue by cryptomilk** [nrenner/brouter-web#322]
Would it be possible to support to export in FIT file format?

The FIT documentation is included in the FIT SDK archive (http://www.thisisant.com/resources/fit/).

**Comment by rkflx** [comment]
@cryptomilk: If you don't mind the question: What's your use case for exporting FIT files?

Did Garmin scrape GPX import from their newer devices? Is there an app which only takes FIT files, but no GPX?

(Importing FIT might also be worth considering, though, to avoid having to convert FIT to GPX with GPSBabel before viewing recorded tracks.)

**Comment by cryptomilk** [comment]
I have a Garmin Fenix Smartwatch, if you only import a GPX, the track is displayed on the map, but thats it..

With a FIT file from Garmin you get turn instructions. The watch e.g. informs you that in 100m there is a turn left or right. I think this is part of the FIT file format but GPX doesn't have such an extension to store such information.

I guess it is the same for other Garmin devices.

**Comment by cryptomilk** [comment]
So currently I create a GPX track with Brouter, save it, import it in Garmin Connect and send it to the device. I would love if I would not have to use Garmin Connect but directly put it on my watch.

**Comment by nrenner** [comment]
I'm generally unsure about the way forward with formatting.

The currently supported formats are own implementations in the server and I personally would be a bit reluctant to implement more this way. I haven't found a JavaScript GPX to FIT converter on a quick search though.

The GPX formatter supports various turn instruction styles, as every app seems to have their own, see [OsmTrack.java](https://github.com/abrensch/brouter/blob/0841216cda47d3327b039e6db00c253e86d0948d/brouter-core/src/main/java/btools/router/OsmTrack.java#L403) (search for `turnInstructionMode`).

Are you sure that Garmin doesn't support turn instructions in GPX?

**Comment by rkflx** [comment]
> I guess it is the same for other Garmin devices.

AFAIK for Garmin Edge devices (i.e. cycling), you've got the following options for a free-software-only workflow:

A) Import track as GPX file, enable turn instructions on the device's course selection screen.
  - Calculated on-device
  - Rerouting possible (e.g. after a missed turn)
  - Turns are shown embedded in the map (exactly where they belong) and additionally as a pop up dialog with a zoomed-in map

B) Use another app or website (e.g. https://cycle.travel) to create a TCX file, and make sure to select the option to embed turn instructions as "course points".
  - Calculated in advance by the respective app or website
  - No rerouting possible
  - Turns are shown as POIs on the map and pop up a text notification when riding over them (so they are usually placed some distance before a turn).

You could try converting the GPX to FIT with GPSBabel, hoping to trigger on-device turn instructions on the Fenix. However, I guess it's more likely the turn instructions are calculated in advance on Garmin Connect.

Is your Fenix able to show TCX course points (you can try with https://cycle.travel), and if so, are they similar to what you get from Garmin Connect?

**Comment by tbsmark86** [comment]
FYI: for a GPX to FIT convert; I've used:
   https://gitlab.com/nwholloway/fit-route
To include the turn instructions I enhanced it a bit:
  https://gitlab.com/tbsmark86/fit-route

Note that as an extra tool allows to do some fine-tuneing on the turn instructions; which in my opinion is almost always needed.

**Comment by cryptomilk** [comment]
Thanks Tobias, I will test it!

**Comment by rkflx** [comment]
> FIT file export is that it has a standard way of marking up turn-by-turn instructions

That's interesting, could you expand on what "standard way" means in terms of interpretation by devices? So far I've found an Excel table in the FIT SDK (Profile.xlsx) listing different turn-by-turn course point types. For TCX, its [XSD schema](https://www8.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd) also has turn-by-turn related course point types (a smaller number, though, so FIT might be a better fit indeed). So, is there any additional difference in how devices display TCX and FIT course points?

To expand on my previous comment: It might be possible to write an XSLT transformation to convert from BRouter's GPX (with one of the turn instruction styles enabled) to TCX. Although not sure how to handle the course point offset along the route, might need changes in BRouter (AFAICS this is currently missing from fit-route too).

> using the Wahoo Bolt - fit files seems to be the only way.

Even if I did not get an answer regarding the Fenix, could you test again whether your Wahoo Bolt supports course points in TCX files from https://cycle.travel? "Wahoo" is mentioned in their download dialog, at least. If not, BRouter or BRouter-Web might have to support FIT export (and possibly import) anyway at some point in the future. Perhaps you could even contribute your FIT code?

> fine-tuneing on the turn instructions

This would be nice for sure. BRouter-Web already allows to add POIs (including export and import as waypoints). It should not be too hard to also handle course points in a similar way (with waypoints, `rtept` or similar fallbacks when exporting to formats without appropriate support).

**Comment by rkflx** [comment]
I had the chance to get someone to test FIT course points on a Garmin Edge 810 using [tbsmark86/fit-route](https://gitlab.com/tbsmark86/fit-route), here is what I got back:

![fit-tbt-test](https://user-images.githubusercontent.com/27236544/89277264-e5d0ad80-d644-11ea-9de5-fc39a388134e.png)

As you can see, it mostly works, but starting at 17 all icons are clearly wrong. Showing a sharp right symbol when in reality you have turn sharply left might even be considered dangerous and therefore is probably not something BRouter-Web should do by default.

I could not see anything wrong in the javascript implementation at first glance, so either it is an issue in the device's firmware or the spec has it mixed up. Here is my test file so you can test on your device and report back: [fit-tbt-test.zip](https://github.com/nrenner/brouter-web/files/5021262/fit-tbt-test.zip)

**Comment by tbsmark86** [comment]
Seems like this will very fast result in problems with supporting all kinds of device because every device has his own bugs and quirks :)

>  but starting at 17 all icons are clearly wrong.

I've tested the file on my Wahoo (Element Bolt) and Symbol 17-22 do point in correct direction although they are only simple arrows.  Symbol 23-25 only use the generic icon.
For me my solution worked well. Longest route was about 400 km and over 100 instructions.

> Even if I did not get an answer regarding the Fenix, could you test again whether your Wahoo Bolt supports course points in 
> TCX files from https://cycle.travel? "

Yes this seems to work (for a short test route). 
But: I've tryed tcx in the past (manually converted from gpx) and it was not reliable. At some point during (long) routes the instructions stopped showing up.
Another disadvantage is that there are now slight/straight left/right which sometimes is important.

However: For the 'average' user (with normal length rides up to maybe 100 km) the TCX way is probably more usable.
Because importing fit files with the Wahoo is not possible using the app. You need to use a hidden feature to enable android usb file transfer: https://trainerday.com/load-workouts-onto-your-wahoo-elemnt-on-a-mac/

**Comment by rkflx** [comment]
Thanks for testing! It would be interesting to know how newer Garmin devices are handling symbols 17 to 25. Paging @craftyguy to see if he could help test with his Edge 130 (see my previous comment). Also: Anybody out there with an Edge 830 or 1030?

If only older devices are affected, maybe it is enough to show a warning, or to provide an option in the UI or in a config file to remap missing/wrong symbols to known working ones. I'd agree that often the more fine-grained instructions in FIT files can prove quite helpful.

> importing fit files with the Wahoo is not possible using the app

Too bad, but it's helpful to know both TCX and FIT might be needed by users. (OTOH, https://youtu.be/fjV0EUVgytM?t=457 shows an import UI of the Wahoo app which claims to support .fit, .gpx and .tcx -- was this removed recently or is it not working as intended?)

The Garmin Connect app seems to be even more restricted, since apparently it only supports importing GPX, and only if it has a network connection (making USB OTG the go-to option in a mobile/offline/free-software-only scenario, I guess).

@cryptomilk It would still be helpful to know whether your Fenix is able to import TCX files with turn instructions (e.g. from https://cycle.travel/map), if you've got a spare minute.

---

@tbsmark86 Would you be interested in MRs against fit-route? There are some fixes I wrote a while back, including for a case where on a Garmin Edge the FIT file caused turn instructions and even the track itself to disappear completely mid-ride.

Regarding implementing FIT and/or TCX file support in BRouter-Web (i.e. client-side instead of server-side), as far as I am aware @nrenner wanted to look into moving assembly of the route download to the web client, to get rid of the extra server request. Not sure about the state of that, but it's probably a good idea to wait for it.

**Comment by craftyguy** [comment]
I loaded it up on my Edge 130, but there doesn't appear to be a way to display an overview of navigation steps like [the earlier comment here](https://github.com/nrenner/brouter-web/issues/322#issuecomment-668489614).. The 130 is pretty limited, I might have to actually ride the route to insure that the directions are correct (lol), unless someone else knows how to get at that information some other way on this device.

Here's what Garmin has to say is available on the 130 when viewing a course: https://www8.garmin.com/manuals/webhelp/edge130/EN-US/GUID-BBE80869-F78B-4D8E-99E2-491C5BF89B73.html

**Comment by cryptomilk** [comment]
Starting tomorrow I will be on holiday for one month finally. Then I will have the time to test it and give feedback.

**Comment by rkflx** [comment]
> I might have to actually ride the route to insure that the directions are correct (lol)

@craftyguy No worries, there's nothing special about the route. Thanks for the swift test, though!

I simply placed a marker for each turning type on a arbitrary route and added its number and name according to [types.js](https://gitlab.com/tbsmark86/fit-route/-/blob/master/public/js/fit/types.js). That's easy to replicate, but I can create a custom route in your area as well (see a git checkout of brouter-web for my email address, if you are interested).

**Comment by craftyguy** [comment]
Email sent!

**Comment by fab33** [comment]
> 
> 
> I had the chance to get someone to test FIT course points on a Garmin Edge 810 using [tbsmark86/fit-route](https://gitlab.com/tbsmark86/fit-route), here is what I got back:
> 
> As you can see, it mostly works, but starting at 17 all icons are clearly wrong. Showing a sharp right symbol when in reality you have to turn sharply left might even be considered dangerous and therefore is probably not something BRouter-Web should do by default.
> 
> I could not see anything wrong in the javascript implementation at first glance, so either it is an issue in the device's firmware or the spec has it mixed up. Here is my test file so you can test on your device and report back: [fit-tbt-test.zip](https://github.com/nrenner/brouter-web/files/5021262/fit-tbt-test.zip)

Works fine with my Garmin Edge Explore with last firmware

![669](https://user-images.githubusercontent.com/10790326/101501772-6cd5bf80-3970-11eb-845c-b6a7250bd7a1.png)
![674](https://user-images.githubusercontent.com/10790326/101501776-6e06ec80-3970-11eb-8d79-d9c9b0a2a48e.png)
![677](https://user-images.githubusercontent.com/10790326/101501778-6e9f8300-3970-11eb-97e8-8068462986d8.png)
![679](https://user-images.githubusercontent.com/10790326/101501781-6e9f8300-3970-11eb-9539-4137b1677578.png)
![694](https://user-images.githubusercontent.com/10790326/101501782-6f381980-3970-11eb-87fa-dcbfa13f1d59.png)
![698](https://user-images.githubusercontent.com/10790326/101501784-6fd0b000-3970-11eb-99d5-65492ffaec66.png)
![702](https://user-images.githubusercontent.com/10790326/101501787-6fd0b000-3970-11eb-839d-10350e0c5438.png)

**Comment by ravenfeld** [comment]
Hello, I am interested in the functionality. For the moment I use https://www.plotaroute.com as soon as I need to run errands.
The point courses can be turn indications but I also use them for refuelling for example on a race.
I remove all the turn indications and I put my own information so that on my watch or gps I have only the information I need.
For the moment I trace with Brouter because more background map and I import in plotaroute after.  

In any case I am very good project.

**Comment by ravenfeld** [comment]
I don't know if it can help but before using plotaroute I was using this application to convert. : https://runningbadger.blogspot.com/2015/08/a-tool-to-help-with-navigation-on.html

**Comment by nrenner** [comment]
We now do formatting in the client, see [Export.js](https://github.com/nrenner/brouter-web/blob/327f9362ccb94bfd79a21021cd2f460a804967d9/js/control/Export.js#L133-L146) and [formats](https://github.com/nrenner/brouter-web/tree/master/js/format), so it should be easier now to add additional formats like FIT and/or TCX in JavaScript.

Would you be interested in submitting a PR?

**Comment by tbsmark86** [comment]
I did some work for this. Seems to load (on my wahoo) but I'm not happy with the code.
Commit (wip!):
https://github.com/tbsmark86/brouter-web/commit/227f4304b2dece97d48c6dabfc6d4a983fa19ff0

Questions:
* Is there any way to get the distance between two geojson points (required for valid fit)
* Because the fit encoder is not a lib its now included as lot of low-level stuff. Seems strange? Do I need to create a separate package like nrenner/togpx ?
* Also how to attribute the original author? Luckily it's MIT License.
* The profile value turn-instructions "auto-choose" seems to be really "never"? This kind of defeat the advantage of FIT. Also is very annoying during my tests because I have to reselect it on every code change. Can't this be made permanent active?
* Is there no kind code-splitting? Seems like a waste that all this code is loaded every time

**Comment by rkflx** [comment]
Nice, thanks for working to merge parts of your fork of fit-route (which I've been a happy user of for a long time now) directly into BRouter-Web.

> The profile value turn-instructions "auto-choose" [...] is very annoying during my tests because I have to reselect it on every code change.

While a modified profile will be `POST`ed to the server when customizing the profile to use a different `turnInstructionMode`, that profile is not added to the `profile` parameter in the URL or the `routingprofile` local storage variable. Thus after reloading the page you'll get the default profile instead of retaining the modified profile still existing on the server. This also means sharing the URL when a profile has been customized might result in a different routing result, which is not ideal. However, if and how to fix this is off-topic here.

For my own usage I simply modified the routing profiles directly (i.e. all `*.brf` files on my local installation), which should work for you too while developing:
```
# Use OsmAnd turn instructions by default (needed for fit-route)
assign turnInstructionMode = 3
```

For production usage, you might want to modify BRouter-Web as follows:
- Do not include TBT instructions if `turnInstructionMode` in the profile is `none` or missing.
- Include TBT instructions if `turnInstructionMode` is set to `auto-choose` or `fit-style` (to be added, internally this would be an alias for the `osmand-style` code path).
- If set to anything else, either also include the standard `fit-style` TBT instructions or show an error message. (The latter is probably more bureaucracy than helpful, so I'd go with the former.)
- Note: This is also a nice architectural customization point: It would be very easy to provide a `fit-style-Edge810` option here to cater to the buggy firmware of that device (see discussion above), without overloading the "Export" UI with lots of checkboxes and help texts.

AFAICS this way we should not require any changes to BRouter (ignoring the deprecated old-style download button for a moment), only changes to the profiles for the `fit-style` option to show up in the UI would be necessary (while not strictly needed, probably a good idea for consistency in the long-term).

**Comment by tbsmark86** [comment]
This is not the right place but some observations about turn instructions while testing this ...

Problem 1)
[Duplicate turns on segment border](https://brouter.de/brouter-web/#map=16/52.5196/13.3121/osm-mapnik-german_style,route-quality&lonlats=13.316964,52.51942;13.315409,52.517945;13.312426,52.518349)
The first segment ends with 'left' and the second starts with 'straight' at the same coordinate.

Is this a Bug in the Exporter and the Segment join should simply ignore the duplication? 
Or is this a bug in the router that it should not generate turn instructions right at the start of route?
At first I prefer the second solution but maybe there are other examples where the previous segment has no turn so ...

My Bolt didn't have a problem with this - only the first turn was visible and he jumped over the second one.

----
Problem 2)
[Useless/Wrong Turn at Segment Border](https://brouter.de/brouter-web/#map=15/52.5281/13.2502/osm-mapnik-german_style,route-quality&lonlats=13.254404,52.522802;13.24952,52.523941;13.247194,52.525412)
There a 'left' turn on the straight road (duplicate again)

Not sure if the OSM data is missing here - there is a combined cycleway/sidewalk along the road.

---
Problem 3)
When exporting a track as gpx and importing it as a route again some turns can be totally wrong i.e. in the opposite direction.

[Re-Imported Track](https://brouter.de/brouter-web/#map=18/52.51996/13.31829/osm-mapnik-german_style,route-quality&lonlats=13.320183,52.520053;13.318819,52.519207;13.317501,52.519505)
The original track had one segment. Here the turn is left - but it should be right! This also is an example without duplication at the segment border and the turn only in the second segment.


All these problems appear on my typical use case: I've got a gpx track for an event. However I prefer turn-by-turn navigation. So each  invalid turn does cause me an extra u-turn and a switch to the map screen :/

**Comment by nrenner** [comment]
> Problem 1)
> Problem 2)
> Problem 3)

See also [brouter#282 Voice hint for route point on junction node](https://github.com/abrensch/brouter/issues/282) and #356/#369.

[brouter#441](https://github.com/abrensch/brouter/pull/441) will address this on the server side, not sure what to do in the client yet, probably adding an overlap when requesting segments.
