### ISSUE TITLE
RouteLoader: infinite loop when 'lastknowngood' not initialized

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#326]
When the first guess is already > `_maxTrackPoints` then the slider `data('lastknowngood')` is never initialized, which results in an infinite loop in `findLowestTolerance`.

Example is this very short route:
http://localhost:3000/#map=17/47.66306/9.36778/osm-mapnik-german_style&lonlats=9.366639,47.66421;9.367647,47.661175

@printpagestopdf Could you have a look, please?

**Comment by printpagestopdf** [comment]
Oh will look at it as soon as possible

**Comment by printpagestopdf** [comment]
Yes, you are right, initialization is missing. To add this line should solve the problem:

diff --git a/js/plugin/RouteLoaderConverter.js b/js/plugin/RouteLoaderConverter.js
index 05de571..ad5a6fc 100644
--- a/js/plugin/RouteLoaderConverter.js
+++ b/js/plugin/RouteLoaderConverter.js
@@ -99,6 +99,7 @@ BR.routeLoader = function(map, layersControl, routing, pois) {
             var guessedTolerance = this.guessSimplifyTolerance(this._trackPoints);
             $slider.data('guess', guessedTolerance.toFixed(20));
             $slider.val(0);
+            $slider.data('lastknowngood',0);^M
             this._options.simplifyTolerance = guessedTolerance;
             this.refreshTestLayer();
         },

Because it is only one line, could you add it directly or do I have to make a new pull request?

**Comment by nrenner** [comment]
I found an additional issue with that route, where the guess is already exceeding the max limit.

I'm working on it, trying a different approach.

**Comment by nrenner** [comment]
I gave up on my approach due to taking me too much time and made a simple fix instead in #327.

The idea was to let the simplify algorithm return all computed point to segment distances (= tolerances) instead of the points by calling it with a tolerance of 0 and sorting the resulting array in descending order. In the most simple case, the array index would represend the number of returned nodes for the corresponding tolerance entry.

So this could be used to lookup the minimum tolerance for max points, as steps for the slider and perhaps for better guessing.

Issues I had so far were float comparisons and finding a better float tolerance than epsilon, and properly accounting for nested local maxima. I got it working for some cases but still had issues with others.
