### ISSUE TITLE
route line fully covers street names - set default transparency slider value to partially transparent.

### ISSUE THREAD

**Issue by matkoniecz** [nrenner/brouter-web#36]
The pink line fully covers street names. I noticed that I need separate tab for map to check road names of route.

I propose avoid fully covering road - by making line partly transparent or by offsetting it from road.

Maybe change style only on high zooms.

I prefer old style (I am pretty sure that there was a blue, partially transparent line).

**Comment by poutnikl** [comment]
Why not to use similr approach as the one used by Elevate vector map theme for OpenAndromaps for Locus ?

http://www.openandromaps.org/en/legend/elevate-mountain-hike-theme

* Hiking routes are rendered below paths and tracks starting at zoom level 14 (OruxMaps: 15), till level 13 (OruxMaps: 14)transparent above them.
International and national hiking routes are magenta.
Regional hiking routes are green.
Local and other hiking routes are yellow.

* Cycling routes are rendered below streets starting at zoom level 14 (OruxMaps: 15), till level 13 (OruxMaps: 14) transparent above them.
International and national cycling routes are red
Regional cycling routes are violet
Local cycling routes are turquoise
Mountain bike routes are greenish yellow

**Comment by matkoniecz** [comment]
> there is the tranparency level slider at the right edge of the left panel. Use it to have both the route and the names visible.

Thanks! I will change title of issue as I think that different default would be better (most people will never notice slider).

**Comment by matkoniecz** [comment]
For me 67% works well - both route is visible and street names are readable.

**Comment by poutnikl** [comment]
It is for me hard to imagine I would not notice it..  :-)    Perhaps neon blinking ? :-D (joking)

**Comment by nrenner** [comment]
Thanks for the constructive feedback.

The old route line style simply was the Leaflet standard (which [has changed](https://github.com/Leaflet/Leaflet/commit/2e9141fa985dc074f61ddbf5441614c17bd4f59f) in the upcoming version). The transparent (0.5) blue color had a bad contrast especially on the OpenCycleMap. Changing the color has been requested on the BRouter Group [\[1\]](https://groups.google.com/d/msg/osm-android-bikerouting/pZcuyVegHCM/R2YQXW4wLwEJ)[\[2\]](https://groups.google.com/d/msg/osm-android-bikerouting/NzTAw2YZnQw/IcA8_BMdxNsJ).

I might have gone too far for maximum contrast (opacity 1.0), will think about making it more transparent initially.

At this point, I'm a bit reluctant to making things more complicated by introducing zoom- or layer-dependant styling.

What I would like to investigate are new CSS features (ideally having a Leaflet plugin I just need to add):

* [blending](https://drafts.fxtf.org/compositing-1/) tiles and path instead of just overlaying with some opacity.
* [filters](http://www.html5rocks.com/en/tutorials/filters/understanding-css/) to 
adjust the background layers for better contrast, see [leaflet-tilefilter](https://github.com/humangeo/leaflet-tilefilter).

**Comment by poutnikl** [comment]
I agree with keeping things simple yet effective. 

An opaque but dashed route line would make sense too, keeping well visible both the route and the road style as well.

**Comment by matkoniecz** [comment]
Thanks!
