### ISSUE TITLE
overpass-layer error: Each LinearRing of a Polygon must have 4 or more Positions

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#396]
To reproduce:
1. add overpass layer, e.g. tourism/Camp site
2. select added overpass layer (Camp site), wait until loaded
3. close layer switcher / side bar
4. -> Error in console, loading message remains

```
Uncaught Error: Each LinearRing of a Polygon must have 4 or more Positions.
    at Object.polygon (overpass-layer.js:3354)
    at Object.difference (overpass-layer.js:3027)
    at KnownArea.check (overpass-layer.js:35693)
    at RequestBBox.needLoad (overpass-layer.js:34479)
    at RequestBBox.mayFinish (overpass-layer.js:34483)
    at overpass-layer.js:32280
    at Array.forEach (<anonymous>)
    at OverpassFrontend._overpassProcess (overpass-layer.js:32275)
    at OverpassFrontend.<anonymous> (overpass-layer.js:32605)
    at overpass-layer.js:23185
```

Looks like a [@turf/difference](https://github.com/Turfjs/turf/tree/master/packages/turf-difference) issue, maybe because of overlapping bbox sides. Maybe already fixed in latest version, overpass-frontend [is using ^6.0.2](https://github.com/plepe/overpass-frontend/blob/78928c47ec885f04461db7d785dc1d411a42c507/package.json#L24) (haven't checked which version is actually resolved/used), [latest is 6.3.0](https://github.com/Turfjs/turf/blob/84110709afda447a686ccdf55724af6ca755c1f8/packages/turf-difference/package.json#L3).

@stesie do you want to have a look?

**Comment by stesie** [comment]
sure :)

So, first of all, yes the overpass-layer version we're using (3.0.0) has @turf/difference bundled in version 6.0.2
Please note, that we're using its' browserified dist version, since our build process doesn't handle the require statements well, that exist in the overpass-layer module.

And yes, as you suppose, it's a bug w/ @turf/difference, due to overlapping bbox sides :)

By hiding the layer switcher the bbox grows, yet the southern and northern edge obviously remain the same.

The following little test script shows this, ... and it fails with version 6.0.2, but works with 6.3.0

```js
const difference = require("@turf/difference")

const a = {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[9.95908498764038,49.7960939701678],[9.978911876678467,49.7960939701678],[9.978911876678467,49.79909957355378],[9.95908498764038,49.79909957355378],[9.95908498764038,49.7960939701678]]]}}
const b = {"type":"Feature","properties":{},"geometry":{"type":"Polygon","coordinates":[[[9.96085524559021,49.7960939701678],[9.977141618728638,49.7960939701678],[9.977141618728638,49.79909957355378],[9.96085524559021,49.79909957355378],[9.96085524559021,49.7960939701678]]]}}

console.log(difference(a, b));
```

If I rebuild overpass-layer w/ recent version of @turf/difference and include this in brouter-web it works like expected.

I'll file a bug report upstream and ask @plepe to rebuild the package :)

**Comment by stesie** [comment]
Just filed https://github.com/plepe/overpass-layer/issues/6
