### ISSUE TITLE
toggle information panels

### ISSUE THREAD

**Issue by jotpe** [nrenner/brouter-web#40]
On mobile devices the information panels on the left side (options, route, download...) take 100% of the screen. I saw it on IPhone 5 and Nexus 4.
A button respectively a http parameter which toggles this information panels off and on could be helpful.
Image the current situation: you send a complicated route to somebody via permalink via mail on his mobile device, but the recipient cannot use it, because he cannot see any map tiles.

![img_0188](https://cloud.githubusercontent.com/assets/3539168/11927309/f606666a-a7cb-11e5-83d2-9321d39a9df3.JPG)

Johannes

**Comment by poutnikl** [comment]
Based what the author said in past, the Brouter-web design was not originally intended for mobile devices, so it has various functionality issues related to used web technologies ( at least until recently ). If ever used in Android, than definitely in Landscape mode. The author reportedly works on better mobile support for future versions.

**Comment by nrenner** [comment]
As poutnikl already said, I have not given mobile support any attention yet, but as there are several requests, I plan to look into what needs to be done.

Making the left panel collapsible would be the first thing to do and is planned anyway. The individual sections are separate components and the idea was to collapse them into buttons so that each could be opened seperately, like the layer switcher. But will need to see how this works out.

**Comment by bagage** [comment]
Fixed in master via #56. Hopefully we can release it any time soon!
