### ISSUE TITLE
Layer "Mapillary" is currently not populated with coverage 

### ISSUE THREAD

**Issue by cmuerau** [nrenner/brouter-web#432]
On June 10, 2021, Mapillary announced a [Platform update being live](https://forum.mapillary.com/t/platform-updates-are-live/4953) with a lot of detail changes missing. Since then discussion there and in other threads as well tries to figure out _all_ changes on all affected apps, instances, etc.

Is it possible that the API change from v3 to v4 is responsible for currently not populating the layer with image positions?

**Comment by rkflx** [comment]
Thank you for the heads-up!

The issue is that the domain `d6a1v2w10ny40.cloudfront.net` used for serving the coverage tiles cannot be resolved anymore (see error console in your browser's dev tools).

Once the dust of the Mapillary migration has settled, we can try to find the new tiles URL / API endpoint (possibly with an API token to add to [keys.template.js](https://github.com/nrenner/brouter-web/blob/master/keys.template.js)), and update [mapillary-coverage-raster.geojson](https://github.com/nrenner/brouter-web/blob/e50372ef723bad259e85d3b0e095b26f47e98fca/layers/extra/mapillary-coverage-raster.geojson#L13).

However, the [new v4 API docs](https://www.mapillary.com/developer/api-documentation) only reference vector tiles so far, while we used raster tiles before. This might need more involved changes.

If a solution is not in sight before the next BRouter-Web release, I'd suggest to disable the overlay for now, since there is no point in shipping something broken.

See also #153 and #289.

**Comment by nrenner** [comment]
I haven't found any comment on the raster tile layer, only a question without answer: "[New Mapillary TMS url?](https://forum.mapillary.com/t/new-mapillary-tms-url/5823)".

So switched to vector tiles, now that we have MapLibre GL JS integrated, see d5a6a0a.

**Comment by govvin** [comment]
Glad to see this back, and have a question about the Mapillary layer. 

Is it possible to color the layer by capture date, similar to an option found from Mapillary's web viewer?
![image](https://user-images.githubusercontent.com/5821688/180888044-b68c94a1-2a75-4e5a-8aa8-710166b6f244.png)
