### ISSUE TITLE
Refusing to take this path

### ISSUE THREAD

**Issue by thany** [nrenner/brouter-web#488]
Why does it refuse to take this road?

![image](https://user-images.githubusercontent.com/152227/160259459-e954f674-4d43-460a-a22f-6f40c8c1aab0.png)

http://brouter.de/brouter-web/#map=16/34.2247/135.5756/osm-mapnik-german_style&lonlats=135.576133,34.227003;135.575709,34.2244;135.575194,34.222821;135.579293,34.220833&profile=shortest

It doesn't do it on any profile, with or without waypoints. It's a perfectly good road to drive on, but even for walking it's avoided like the plague.

A workaround would be to add a "any" profile where it would follow any line that it can find, regardless of what it is. More preferably, it would follow a road that is there, perfectly ready to be driven on, cycled on, or even walked on, given a profile that is good for it.

**Comment by mjaschen** [comment]
This road is tagged with `access=private` and therefore not suitable for routing.

https://www.openstreetmap.org/way/588042692

**Comment by thany** [comment]
But on "shortest" shouldn't it take any path regardless?

**Comment by mjaschen** [comment]
No, because access restrictions are applied even in the “Shortest” profile, see [the profile source](https://github.com/abrensch/brouter/blob/master/misc/profiles2/shortest.brf#L30-L60) for details.

If you want to ignore the restrictions you have to adjust the profile (that's possible in the profiles tab in BRouter-web).
