### ISSUE TITLE
Itinerary not displaying anything

### ISSUE THREAD

**Issue by bagage** [nrenner/brouter-web#61]
I'm trying to check what Itinerary tab should display but I cannot make it work. I updated brouter from 1.4.2 to 1.4.8, updated `config.js` to enable transit, but still when I draw a route nothing is shown in the Itinerary tab.
Digging a bit further, there is no field `segments[i].feature.iternity`, so… am I missing a step? Do you plan to use it on brouter-web website @nrenner?

**Comment by nrenner** [comment]
The Itinerary is part of a multimodal transit routing demo developed by abrensch. There is an instance at http://brouter.de/brouter-web-im/ but the server is not running.

I also used this online server to test, but mainly some temporarily inserted static text. The server part is different from the standalone server and is in the [brouter-mem-router](https://github.com/abrensch/brouter/tree/master/brouter-mem-router) package, but not easy to set up because of the data it requires.

I plan to keep and maintain this inside the client as long as the code is not flexible enough to be extended. But we don't need the Itinerary on mobile. For examples on how the output looks like, there are some screenshots in [these slides](https://frab.fossgis-konferenz.de/system/event_attachments/attachments/000/000/065/original/transit_osm.pdf?1467805777) by abrensch (e.g. page 17).

**Comment by bagage** [comment]
I think I managed to not break the code of it even without being able to test (hopefully :)).
