### ISSUE TITLE
Use the newer library?

### ISSUE THREAD

**Issue by 0709wiwiwi** [nrenner/brouter-web#750]
**A question on the Brouter web timeline planning.**
As the new Brouter library is publisched some time ago
Will the new gpx navigation track export be available ? 

I thought about the next presentation.
**BRouter web planner export selection menu.**

_Most optimal is to keep the current Brouter web selection menu as is._

**Suggestion.**
The default auto-choose selection exports a track with discrete attached instructions in trackpoints. 
This export is compatible with both Android **Locus map** and **Cruiser** app navigation.

**The Current Brouter web export selector.**
 
![turnInstructionModePanel](https://github.com/nrenner/brouter-web/assets/54167201/1f669b9d-026c-4275-b7a9-6704bff32f99)

**TurnInstructionMode export selection.**

- none (gpx trk) (standard naked trk)
- **auto-choose (gpx trk + navtrkpt) (Locus and Cruiser)** **_NEW_**
- locus-style (gpx trk + navwpt)
- osmand-style. (gpx trk + navrtept)
- comment-style. (gpx trk + comment)
- gpspies-style. (gpx trk + navwpt)
- oruxmaps-style. (gpx trk + navwpt)
 
The map display results this by the different export modes 
- Many discrete navigation trackpoints **DO NOT** pollute the map display. 
- Many navigation waypoints or routepoints **DO** pollute the map display.

**Comment by nrenner** [comment]
> As the new Brouter library is publisched some time ago
> Will the new gpx navigation track export be available ?

- client-side export needs a separate implementation and I don't give time estimates
- In the meantime you can use the fallback server-side download (small middle button in export dialog)
- the turnInstructionMode selection is automatically generated from the profile, e.g. [trekking](https://github.com/abrensch/brouter/blob/993a3aa85987553434b8fe7be5c650f04a2b05bc/misc/profiles2/trekking.brf#L46), `2=locus-style` is the new one:   
`assign turnInstructionMode          = 1     # %turnInstructionMode% | Mode for the generated turn instructions | [0=none, 1=auto-choose, 2=locus-style, 3=osmand-style, 4=comment-style, 5=gpsies-style, 6=orux-style, 7=locus-old-style]`
- your screenshot seems to be old, either because of caching (try Ctrl-F5 to force refresh) or a non-updated profile (try trekking)

**Comment by 0709wiwiwi** [comment]
> fallback server-side download (small middle button in export dialog)    👍

I expected it not to be there due to the msg "download from server (deprecated).
