### ISSUE TITLE
Add content of custom profile to permalink

### ISSUE THREAD

**Issue by matkoniecz** [nrenner/brouter-web#9]
Currently it is quite irritating to make queries with a custom profile - it is necessary to upload it every time (switch to file manager, find some specific file, open it, copy content, select upload).

Wit saving it in permalink it would be possible to just have bookmark an just use it. It would be also easier to share custom profiles.

**Comment by poutnikl** [comment]
Profiles can easily reach 20 kB.. Embedding of URL pointing to the profile , if possible, is probably way to go,

**Comment by nrenner** [comment]
Will need to investigate what the best solution is, but current idea is to offer saving/exporting the profile as GitHub Gist. And probably in addition loading from and linking to an URL as a flexible option.

**Comment by jotpe** [comment]
Maybe the solution at overpass-turbo.eu s share button is an inspiration?

It saves the query on the server and generates a short link to share.

**Comment by nrenner** [comment]
This is similar to what @poutnikl meant in #26 and what technically would sort of already work.

But saving user content on the server and thus taking responsibility for it (e.g. backup) is what we (@abrensch?) are trying to avoid.

And I kind of like the Gist idea because when logged in to GitHub it could also give you a version history, I think. But will need to evaluate and see if possible and what the effort would be.

**Comment by abrensch** [comment]
> But saving user content on the server and thus
> taking responsibility for it (e.g. backup) is what
> we (@abrensch?) are trying to avoid.

What's the legal situation from a publisher's point of view? Especially if we display the custom profiles based on perma-links, we ara basically publishing un-moderated, arbitrary content from non-registered users. Is there any difference whether we load the content from a 3rd-party URL, decode it from a zip/base64 url-parameter or host it on the server-disc?

I guess that if we look for the smallest patch against any of the hosted profiles, it's zip/base64 encoding would normally be suitable for an url-parameter. Whould that be a solution?

**Comment by nrenner** [comment]
No idea about the legal aspect and if it makes a difference where the content is from. But I would feel better if linked profiles are stored externally, this way it is more clear that the content is not from us. I wouldn't be too worried, because it needs user interaction to click on a permalink posted/published by someone else and not by us - but again, don't really know. 

Good point about moderation though, which would be easier if profiles are stored on the server.

Using only a diff as URL parameter is surely a good option, as most custom profiles are probably derived from the hosted ones or are just simple flag switches. It is a bit more involved though and requires some kind of profile versioning to make sure the referenced profile remains unchanged.

**Comment by poutnikl** [comment]
Would be acceptable to implement user accounts in the Brouter-web ?

It could allow to define and keep ( optionally public ) named custom profiles, being just reference to an external URL.   E.g. I could save custom profile with symbolic name My_Ultimate_Trekking_Profile"  :-), refering to 
https://raw.githubusercontent.com/poutnikl/Trekking-Poutnik/Maximizing-Penalty/Trekking-Poutnik.brf

Than permalink could use user symbolic profile name and Brouter would internally refer to URL above and would use it for the routing. 

If profile was private, than for user purpose, 
if profile was public, than as well for sharing.

**Comment by poutnikl** [comment]
Other option would be avoiding user accounts, using in the permalink external URL of user choice.

**Comment by nrenner** [comment]
Closing in favour of #26.
