### ISSUE TITLE
Improve error message if no route found

### ISSUE THREAD

**Issue by ProBackup-nl** [nrenner/brouter-web#99]
After choosing the target/destination, a red popup appears on the map:

> Error: no response from server

or

> Error: target island detected for section 0

3th time (after moving destination marker), a/the route line was displayed.

Firefox 52.5.3 ESR (extended service release)
https://brouter.damsy.net/#map=9/51.8799/5.6387/OpenStreetMap&lonlats=4.367065,52.006865|5.710144,51.60096 
v.0.8.0, profile: Trekking, Original

**Comment by poutnikl** [comment]
Regarding the latter msg, it's usually an expected response, if the user selects such a destination, that is not possible to be reached via allowed OSM ways, according to used profile and OSM data.

Usually, the last mile segment is a road forbidden by the profile, or there are mapping errors in OSM data.

I advice to check if your case is one of above, or provide the link or info about affected location.

You may also check, if the Brouter Application behaves the same for the same start, destination and profile.

If yes, then it is not fault of the Samsung server.

If no, then it may be caused by different OSM data, lookups.dat version or Brouter version.

**Comment by poutnikl** [comment]
Samsung = damsy :-)

**Comment by poutnikl** [comment]
Sorry, I somehow missed the link..

**Comment by poutnikl** [comment]
Brouter generally reports a failed routing, if the route cannot get close enough to destination point, that is out of the OSM way network. This is the case of you desired route. If you move the destination point closer to the road network, the vicinity threshold is not triggered and routing is successful, even if the destination cannot be really reached.
This threshold is rather low, some tens of meters.
